20th time commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,11 +26,24 @@ jobs:
       - name: Install playwright
         run: npm init playwright@latest
       # start storybook
-      - name: Start storybook
-        run: npm run storybook
-      
-      - name: Wait
+      - name: Start Storybook
+        run: yarn storybook --ci --port 6006 &
+      # This command starts Storybook in the background
+      - name: Wait for Storybook to be available
         run: npx wait-on http://127.0.0.1:6006
       # start test-storybook
       - name: Start coverage
         run: npm run test-storybook -- --coverage
+
+      - name: Run tests with coverage
+        run: npm test-storybook --coverage
+
+      - name: Check coverage threshol d
+        run: |
+          COVERAGE=$(grep -o '"statements": [0-9.]*' ./coverage/coverage-summary.json | awk '{print $2}')
+          if (( $(echo "$COVERAGE < 50.0" |bc -l) )); then
+            echo "Test coverage ($COVERAGE%) is below the required threshold of 50%."
+            exit 1
+          else
+            echo "Test coverage ($COVERAGE%) meets the required threshold."
+          fi
